name: PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v3.2.0
    with:
      php-versions: "[\"7.4\", \"8.0\"]"
